### PR TITLE
Compatibility with math-comp master

### PR DESCRIPTION
**Pull request by proux01**
Required in https://github.com/CoqEAL/CoqEAL/pull/15

### CODE REVIEW

**Comment by CohenCyril** [comment]
Dear @erikmd and @proux01, I cannot merge this PR into finmap:master, since I wish to maintain master compatible with the latest released versions of each lib. Could you please pr to a branch called `1.1+mathcomp-dev`?

**Comment by CohenCyril** [comment]
pushed to branch https://github.com/math-comp/finmap/tree/1.1+mathcomp-dev

**Comment by proux01** [comment]
> Dear @erikmd and @proux01, I cannot merge this PR into `finmap/master`, since I wish to maintain `master` compatible with the latest released versions of each lib.

Well, this PR is compatible with *both* math-comp 1.7 and master.

**Comment by proux01** [comment]
CI passes

**Comment by CohenCyril** [comment]
Dear @proux01 I had not read your fix before, my bad...
I am hesitant to introduce such layers of compatibility, I would rather to have two "clean" versions (no ltac) than one which is unreadable.

**Comment by proux01** [comment]
I agree it is a somewhat quick and dirty solution.

My point is:
- it is simple
- it only affects a small portion of the code, which doesn't look likely to be modified a lot
- it could be easily removed, the day support of math-comp <= 1.7 will be dropped

I agree having two versions would be cleaner but it requires a bit more work (maintaining two branches, two opam packages).

Anyway, any solution is fine for me, I was trying to push things forward.

**Pull request merged**
