### PR TITLE
add setfs function to update an fsfun, add key setfs lemmas

### PR DESCRIPTION
**Pull request by palmskog**
Key setter function definition and lemmas for `fsfun`. Some hints on best placement and SSReflect improvements appreciated.

### CODE REVIEW

**Comment by CohenCyril** [comment]
I was rather thinking about something along these lines

**Comment by palmskog** [comment]
@CohenCyril that looks better and more elegant than my solution, but it seems like it breaks `multiset.v`:
```
File "./multiset.v", line 63, characters 50-52:
Error:
Syntax error: 'without' or 'with' expected after [constr:operconstr level 200] (in [constr:operconstr]).
```

**Comment by CohenCyril** [comment]
> @CohenCyril that looks better and more elegant than my solution, but it seems like it breaks `multiset.v`:
> 
> ```
> File "./multiset.v", line 63, characters 50-52:
> Error:
> Syntax error: 'without' or 'with' expected after [constr:operconstr level 200] (in [constr:operconstr]).
> ```

Fixed, not sure it is in the best way, but when you try it will show...

**Comment by palmskog** [comment]
OK, so what should be the next step do you think? Should I try using this in one of my projects right now?

**Comment by CohenCyril** [comment]
> OK, so what should be the next step do you think? Should I try using this in one of my projects right now?

I'm tempted to merge in master, and have your feedback before the next release if that's ok for you.

**Comment by palmskog** [comment]
> I'm tempted to merge in master, and have your feedback before the next release if that's ok for you.

Sounds good to me.

**Pull request merged**
